version: '3'
services:
  postgres:
    image: postgres:14.5-bullseye
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
    depends_on:
      - postgres
